"""Added employee_id to User model

Revision ID: 16431a767286
Revises: b506005a3ab6
Create Date: 2024-10-14 17:53:09.098599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16431a767286'
down_revision = 'b506005a3ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_employee_id', 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
