"""Fixed relationships and backref names

Revision ID: 49758d9fc481
Revises: 3a87e011b635
Create Date: 2024-10-14 19:50:56.426462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49758d9fc481'
down_revision = '3a87e011b635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
